// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMCRequestParams.proto

package src;

public final class CMC {
  private CMC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CMCRequestParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bean.CMCRequestParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
     */
    boolean hasHeader();
    /**
     * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
     */
    src.CMC.CMCRequestParam.Header getHeader();
    /**
     * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
     */
    src.CMC.CMCRequestParam.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
     */
    boolean hasBody();
    /**
     * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
     */
    src.CMC.CMCRequestParam.Body getBody();
    /**
     * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
     */
    src.CMC.CMCRequestParam.BodyOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code com.bean.CMCRequestParam}
   */
  public  static final class CMCRequestParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bean.CMCRequestParam)
      CMCRequestParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CMCRequestParam.newBuilder() to construct.
    private CMCRequestParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CMCRequestParam() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CMCRequestParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 66: {
              src.CMC.CMCRequestParam.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(src.CMC.CMCRequestParam.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 74: {
              src.CMC.CMCRequestParam.Body.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(src.CMC.CMCRequestParam.Body.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.CMC.internal_static_com_bean_CMCRequestParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.CMC.internal_static_com_bean_CMCRequestParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.CMC.CMCRequestParam.class, src.CMC.CMCRequestParam.Builder.class);
    }

    public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bean.CMCRequestParam.Header)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 command = 1;</code>
       */
      int getCommand();

      /**
       * <code>string sip = 2;</code>
       */
      java.lang.String getSip();
      /**
       * <code>string sip = 2;</code>
       */
      com.google.protobuf.ByteString
          getSipBytes();

      /**
       * <code>string uuid = 3;</code>
       */
      java.lang.String getUuid();
      /**
       * <code>string uuid = 3;</code>
       */
      com.google.protobuf.ByteString
          getUuidBytes();

      /**
       * <code>int32 type = 4;</code>
       */
      int getType();
    }
    /**
     * Protobuf type {@code com.bean.CMCRequestParam.Header}
     */
    public  static final class Header extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bean.CMCRequestParam.Header)
        HeaderOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Header() {
        command_ = 0;
        sip_ = "";
        uuid_ = "";
        type_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                command_ = input.readInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                sip_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                uuid_ = s;
                break;
              }
              case 32: {

                type_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.CMC.internal_static_com_bean_CMCRequestParam_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.CMC.internal_static_com_bean_CMCRequestParam_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.CMC.CMCRequestParam.Header.class, src.CMC.CMCRequestParam.Header.Builder.class);
      }

      public static final int COMMAND_FIELD_NUMBER = 1;
      private int command_;
      /**
       * <code>int32 command = 1;</code>
       */
      public int getCommand() {
        return command_;
      }

      public static final int SIP_FIELD_NUMBER = 2;
      private volatile java.lang.Object sip_;
      /**
       * <code>string sip = 2;</code>
       */
      public java.lang.String getSip() {
        java.lang.Object ref = sip_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sip_ = s;
          return s;
        }
      }
      /**
       * <code>string sip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSipBytes() {
        java.lang.Object ref = sip_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int UUID_FIELD_NUMBER = 3;
      private volatile java.lang.Object uuid_;
      /**
       * <code>string uuid = 3;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        }
      }
      /**
       * <code>string uuid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 4;
      private int type_;
      /**
       * <code>int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (command_ != 0) {
          output.writeInt32(1, command_);
        }
        if (!getSipBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sip_);
        }
        if (!getUuidBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uuid_);
        }
        if (type_ != 0) {
          output.writeInt32(4, type_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (command_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, command_);
        }
        if (!getSipBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sip_);
        }
        if (!getUuidBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uuid_);
        }
        if (type_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof src.CMC.CMCRequestParam.Header)) {
          return super.equals(obj);
        }
        src.CMC.CMCRequestParam.Header other = (src.CMC.CMCRequestParam.Header) obj;

        boolean result = true;
        result = result && (getCommand()
            == other.getCommand());
        result = result && getSip()
            .equals(other.getSip());
        result = result && getUuid()
            .equals(other.getUuid());
        result = result && (getType()
            == other.getType());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getCommand();
        hash = (37 * hash) + SIP_FIELD_NUMBER;
        hash = (53 * hash) + getSip().hashCode();
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static src.CMC.CMCRequestParam.Header parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static src.CMC.CMCRequestParam.Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static src.CMC.CMCRequestParam.Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(src.CMC.CMCRequestParam.Header prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.bean.CMCRequestParam.Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.bean.CMCRequestParam.Header)
          src.CMC.CMCRequestParam.HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return src.CMC.internal_static_com_bean_CMCRequestParam_Header_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return src.CMC.internal_static_com_bean_CMCRequestParam_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  src.CMC.CMCRequestParam.Header.class, src.CMC.CMCRequestParam.Header.Builder.class);
        }

        // Construct using src.CMC.CMCRequestParam.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          command_ = 0;

          sip_ = "";

          uuid_ = "";

          type_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return src.CMC.internal_static_com_bean_CMCRequestParam_Header_descriptor;
        }

        @java.lang.Override
        public src.CMC.CMCRequestParam.Header getDefaultInstanceForType() {
          return src.CMC.CMCRequestParam.Header.getDefaultInstance();
        }

        @java.lang.Override
        public src.CMC.CMCRequestParam.Header build() {
          src.CMC.CMCRequestParam.Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public src.CMC.CMCRequestParam.Header buildPartial() {
          src.CMC.CMCRequestParam.Header result = new src.CMC.CMCRequestParam.Header(this);
          result.command_ = command_;
          result.sip_ = sip_;
          result.uuid_ = uuid_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof src.CMC.CMCRequestParam.Header) {
            return mergeFrom((src.CMC.CMCRequestParam.Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(src.CMC.CMCRequestParam.Header other) {
          if (other == src.CMC.CMCRequestParam.Header.getDefaultInstance()) return this;
          if (other.getCommand() != 0) {
            setCommand(other.getCommand());
          }
          if (!other.getSip().isEmpty()) {
            sip_ = other.sip_;
            onChanged();
          }
          if (!other.getUuid().isEmpty()) {
            uuid_ = other.uuid_;
            onChanged();
          }
          if (other.getType() != 0) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          src.CMC.CMCRequestParam.Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (src.CMC.CMCRequestParam.Header) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int command_ ;
        /**
         * <code>int32 command = 1;</code>
         */
        public int getCommand() {
          return command_;
        }
        /**
         * <code>int32 command = 1;</code>
         */
        public Builder setCommand(int value) {
          
          command_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 command = 1;</code>
         */
        public Builder clearCommand() {
          
          command_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object sip_ = "";
        /**
         * <code>string sip = 2;</code>
         */
        public java.lang.String getSip() {
          java.lang.Object ref = sip_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            sip_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string sip = 2;</code>
         */
        public com.google.protobuf.ByteString
            getSipBytes() {
          java.lang.Object ref = sip_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sip_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string sip = 2;</code>
         */
        public Builder setSip(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          sip_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string sip = 2;</code>
         */
        public Builder clearSip() {
          
          sip_ = getDefaultInstance().getSip();
          onChanged();
          return this;
        }
        /**
         * <code>string sip = 2;</code>
         */
        public Builder setSipBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          sip_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object uuid_ = "";
        /**
         * <code>string uuid = 3;</code>
         */
        public java.lang.String getUuid() {
          java.lang.Object ref = uuid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uuid_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string uuid = 3;</code>
         */
        public com.google.protobuf.ByteString
            getUuidBytes() {
          java.lang.Object ref = uuid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uuid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string uuid = 3;</code>
         */
        public Builder setUuid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          uuid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string uuid = 3;</code>
         */
        public Builder clearUuid() {
          
          uuid_ = getDefaultInstance().getUuid();
          onChanged();
          return this;
        }
        /**
         * <code>string uuid = 3;</code>
         */
        public Builder setUuidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          uuid_ = value;
          onChanged();
          return this;
        }

        private int type_ ;
        /**
         * <code>int32 type = 4;</code>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>int32 type = 4;</code>
         */
        public Builder setType(int value) {
          
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 type = 4;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.bean.CMCRequestParam.Header)
      }

      // @@protoc_insertion_point(class_scope:com.bean.CMCRequestParam.Header)
      private static final src.CMC.CMCRequestParam.Header DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new src.CMC.CMCRequestParam.Header();
      }

      public static src.CMC.CMCRequestParam.Header getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Header>
          PARSER = new com.google.protobuf.AbstractParser<Header>() {
        @java.lang.Override
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Header> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public src.CMC.CMCRequestParam.Header getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface BodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bean.CMCRequestParam.Body)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string sessionID = 5;</code>
       */
      java.lang.String getSessionID();
      /**
       * <code>string sessionID = 5;</code>
       */
      com.google.protobuf.ByteString
          getSessionIDBytes();

      /**
       * <code>repeated string lists = 10;</code>
       */
      java.util.List<java.lang.String>
          getListsList();
      /**
       * <code>repeated string lists = 10;</code>
       */
      int getListsCount();
      /**
       * <code>repeated string lists = 10;</code>
       */
      java.lang.String getLists(int index);
      /**
       * <code>repeated string lists = 10;</code>
       */
      com.google.protobuf.ByteString
          getListsBytes(int index);
    }
    /**
     * Protobuf type {@code com.bean.CMCRequestParam.Body}
     */
    public  static final class Body extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bean.CMCRequestParam.Body)
        BodyOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Body.newBuilder() to construct.
      private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Body() {
        sessionID_ = "";
        lists_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Body(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();

                sessionID_ = s;
                break;
              }
              case 82: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  lists_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                lists_.add(s);
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            lists_ = lists_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.CMC.internal_static_com_bean_CMCRequestParam_Body_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.CMC.internal_static_com_bean_CMCRequestParam_Body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.CMC.CMCRequestParam.Body.class, src.CMC.CMCRequestParam.Body.Builder.class);
      }

      private int bitField0_;
      public static final int SESSIONID_FIELD_NUMBER = 5;
      private volatile java.lang.Object sessionID_;
      /**
       * <code>string sessionID = 5;</code>
       */
      public java.lang.String getSessionID() {
        java.lang.Object ref = sessionID_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionID_ = s;
          return s;
        }
      }
      /**
       * <code>string sessionID = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        java.lang.Object ref = sessionID_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LISTS_FIELD_NUMBER = 10;
      private com.google.protobuf.LazyStringList lists_;
      /**
       * <code>repeated string lists = 10;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getListsList() {
        return lists_;
      }
      /**
       * <code>repeated string lists = 10;</code>
       */
      public int getListsCount() {
        return lists_.size();
      }
      /**
       * <code>repeated string lists = 10;</code>
       */
      public java.lang.String getLists(int index) {
        return lists_.get(index);
      }
      /**
       * <code>repeated string lists = 10;</code>
       */
      public com.google.protobuf.ByteString
          getListsBytes(int index) {
        return lists_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getSessionIDBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sessionID_);
        }
        for (int i = 0; i < lists_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 10, lists_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getSessionIDBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sessionID_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < lists_.size(); i++) {
            dataSize += computeStringSizeNoTag(lists_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getListsList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof src.CMC.CMCRequestParam.Body)) {
          return super.equals(obj);
        }
        src.CMC.CMCRequestParam.Body other = (src.CMC.CMCRequestParam.Body) obj;

        boolean result = true;
        result = result && getSessionID()
            .equals(other.getSessionID());
        result = result && getListsList()
            .equals(other.getListsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionID().hashCode();
        if (getListsCount() > 0) {
          hash = (37 * hash) + LISTS_FIELD_NUMBER;
          hash = (53 * hash) + getListsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static src.CMC.CMCRequestParam.Body parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Body parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static src.CMC.CMCRequestParam.Body parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static src.CMC.CMCRequestParam.Body parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(src.CMC.CMCRequestParam.Body prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.bean.CMCRequestParam.Body}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.bean.CMCRequestParam.Body)
          src.CMC.CMCRequestParam.BodyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return src.CMC.internal_static_com_bean_CMCRequestParam_Body_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return src.CMC.internal_static_com_bean_CMCRequestParam_Body_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  src.CMC.CMCRequestParam.Body.class, src.CMC.CMCRequestParam.Body.Builder.class);
        }

        // Construct using src.CMC.CMCRequestParam.Body.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          sessionID_ = "";

          lists_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return src.CMC.internal_static_com_bean_CMCRequestParam_Body_descriptor;
        }

        @java.lang.Override
        public src.CMC.CMCRequestParam.Body getDefaultInstanceForType() {
          return src.CMC.CMCRequestParam.Body.getDefaultInstance();
        }

        @java.lang.Override
        public src.CMC.CMCRequestParam.Body build() {
          src.CMC.CMCRequestParam.Body result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public src.CMC.CMCRequestParam.Body buildPartial() {
          src.CMC.CMCRequestParam.Body result = new src.CMC.CMCRequestParam.Body(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.sessionID_ = sessionID_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            lists_ = lists_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.lists_ = lists_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof src.CMC.CMCRequestParam.Body) {
            return mergeFrom((src.CMC.CMCRequestParam.Body)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(src.CMC.CMCRequestParam.Body other) {
          if (other == src.CMC.CMCRequestParam.Body.getDefaultInstance()) return this;
          if (!other.getSessionID().isEmpty()) {
            sessionID_ = other.sessionID_;
            onChanged();
          }
          if (!other.lists_.isEmpty()) {
            if (lists_.isEmpty()) {
              lists_ = other.lists_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureListsIsMutable();
              lists_.addAll(other.lists_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          src.CMC.CMCRequestParam.Body parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (src.CMC.CMCRequestParam.Body) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object sessionID_ = "";
        /**
         * <code>string sessionID = 5;</code>
         */
        public java.lang.String getSessionID() {
          java.lang.Object ref = sessionID_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            sessionID_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string sessionID = 5;</code>
         */
        public com.google.protobuf.ByteString
            getSessionIDBytes() {
          java.lang.Object ref = sessionID_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sessionID_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string sessionID = 5;</code>
         */
        public Builder setSessionID(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          sessionID_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string sessionID = 5;</code>
         */
        public Builder clearSessionID() {
          
          sessionID_ = getDefaultInstance().getSessionID();
          onChanged();
          return this;
        }
        /**
         * <code>string sessionID = 5;</code>
         */
        public Builder setSessionIDBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          sessionID_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList lists_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureListsIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            lists_ = new com.google.protobuf.LazyStringArrayList(lists_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getListsList() {
          return lists_.getUnmodifiableView();
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public int getListsCount() {
          return lists_.size();
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public java.lang.String getLists(int index) {
          return lists_.get(index);
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public com.google.protobuf.ByteString
            getListsBytes(int index) {
          return lists_.getByteString(index);
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public Builder setLists(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureListsIsMutable();
          lists_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public Builder addLists(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureListsIsMutable();
          lists_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public Builder addAllLists(
            java.lang.Iterable<java.lang.String> values) {
          ensureListsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lists_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public Builder clearLists() {
          lists_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string lists = 10;</code>
         */
        public Builder addListsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureListsIsMutable();
          lists_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.bean.CMCRequestParam.Body)
      }

      // @@protoc_insertion_point(class_scope:com.bean.CMCRequestParam.Body)
      private static final src.CMC.CMCRequestParam.Body DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new src.CMC.CMCRequestParam.Body();
      }

      public static src.CMC.CMCRequestParam.Body getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Body>
          PARSER = new com.google.protobuf.AbstractParser<Body>() {
        @java.lang.Override
        public Body parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Body(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Body> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Body> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public src.CMC.CMCRequestParam.Body getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADER_FIELD_NUMBER = 8;
    private src.CMC.CMCRequestParam.Header header_;
    /**
     * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
     */
    public src.CMC.CMCRequestParam.Header getHeader() {
      return header_ == null ? src.CMC.CMCRequestParam.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
     */
    public src.CMC.CMCRequestParam.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 9;
    private src.CMC.CMCRequestParam.Body body_;
    /**
     * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
     */
    public src.CMC.CMCRequestParam.Body getBody() {
      return body_ == null ? src.CMC.CMCRequestParam.Body.getDefaultInstance() : body_;
    }
    /**
     * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
     */
    public src.CMC.CMCRequestParam.BodyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(8, getHeader());
      }
      if (body_ != null) {
        output.writeMessage(9, getBody());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getHeader());
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getBody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof src.CMC.CMCRequestParam)) {
        return super.equals(obj);
      }
      src.CMC.CMCRequestParam other = (src.CMC.CMCRequestParam) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static src.CMC.CMCRequestParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.CMC.CMCRequestParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.CMC.CMCRequestParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.CMC.CMCRequestParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.CMC.CMCRequestParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.CMC.CMCRequestParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.CMC.CMCRequestParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.CMC.CMCRequestParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.CMC.CMCRequestParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static src.CMC.CMCRequestParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.CMC.CMCRequestParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.CMC.CMCRequestParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(src.CMC.CMCRequestParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bean.CMCRequestParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bean.CMCRequestParam)
        src.CMC.CMCRequestParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.CMC.internal_static_com_bean_CMCRequestParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.CMC.internal_static_com_bean_CMCRequestParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.CMC.CMCRequestParam.class, src.CMC.CMCRequestParam.Builder.class);
      }

      // Construct using src.CMC.CMCRequestParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.CMC.internal_static_com_bean_CMCRequestParam_descriptor;
      }

      @java.lang.Override
      public src.CMC.CMCRequestParam getDefaultInstanceForType() {
        return src.CMC.CMCRequestParam.getDefaultInstance();
      }

      @java.lang.Override
      public src.CMC.CMCRequestParam build() {
        src.CMC.CMCRequestParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public src.CMC.CMCRequestParam buildPartial() {
        src.CMC.CMCRequestParam result = new src.CMC.CMCRequestParam(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.CMC.CMCRequestParam) {
          return mergeFrom((src.CMC.CMCRequestParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.CMC.CMCRequestParam other) {
        if (other == src.CMC.CMCRequestParam.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.CMC.CMCRequestParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.CMC.CMCRequestParam) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private src.CMC.CMCRequestParam.Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          src.CMC.CMCRequestParam.Header, src.CMC.CMCRequestParam.Header.Builder, src.CMC.CMCRequestParam.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public src.CMC.CMCRequestParam.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? src.CMC.CMCRequestParam.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public Builder setHeader(src.CMC.CMCRequestParam.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public Builder setHeader(
          src.CMC.CMCRequestParam.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public Builder mergeHeader(src.CMC.CMCRequestParam.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              src.CMC.CMCRequestParam.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public src.CMC.CMCRequestParam.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      public src.CMC.CMCRequestParam.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              src.CMC.CMCRequestParam.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.bean.CMCRequestParam.Header header = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          src.CMC.CMCRequestParam.Header, src.CMC.CMCRequestParam.Header.Builder, src.CMC.CMCRequestParam.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              src.CMC.CMCRequestParam.Header, src.CMC.CMCRequestParam.Header.Builder, src.CMC.CMCRequestParam.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private src.CMC.CMCRequestParam.Body body_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          src.CMC.CMCRequestParam.Body, src.CMC.CMCRequestParam.Body.Builder, src.CMC.CMCRequestParam.BodyOrBuilder> bodyBuilder_;
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public src.CMC.CMCRequestParam.Body getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? src.CMC.CMCRequestParam.Body.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public Builder setBody(src.CMC.CMCRequestParam.Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public Builder setBody(
          src.CMC.CMCRequestParam.Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public Builder mergeBody(src.CMC.CMCRequestParam.Body value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              src.CMC.CMCRequestParam.Body.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public src.CMC.CMCRequestParam.Body.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      public src.CMC.CMCRequestParam.BodyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              src.CMC.CMCRequestParam.Body.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.com.bean.CMCRequestParam.Body body = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          src.CMC.CMCRequestParam.Body, src.CMC.CMCRequestParam.Body.Builder, src.CMC.CMCRequestParam.BodyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              src.CMC.CMCRequestParam.Body, src.CMC.CMCRequestParam.Body.Builder, src.CMC.CMCRequestParam.BodyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bean.CMCRequestParam)
    }

    // @@protoc_insertion_point(class_scope:com.bean.CMCRequestParam)
    private static final src.CMC.CMCRequestParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new src.CMC.CMCRequestParam();
    }

    public static src.CMC.CMCRequestParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CMCRequestParam>
        PARSER = new com.google.protobuf.AbstractParser<CMCRequestParam>() {
      @java.lang.Override
      public CMCRequestParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CMCRequestParam(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CMCRequestParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CMCRequestParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public src.CMC.CMCRequestParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bean_CMCRequestParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bean_CMCRequestParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bean_CMCRequestParam_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bean_CMCRequestParam_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bean_CMCRequestParam_Body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bean_CMCRequestParam_Body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026CMCRequestParams.proto\022\010com.bean\"\337\001\n\017C" +
      "MCRequestParam\0220\n\006header\030\010 \001(\0132 .com.bea" +
      "n.CMCRequestParam.Header\022,\n\004body\030\t \001(\0132\036" +
      ".com.bean.CMCRequestParam.Body\032B\n\006Header" +
      "\022\017\n\007command\030\001 \001(\005\022\013\n\003sip\030\002 \001(\t\022\014\n\004uuid\030\003" +
      " \001(\t\022\014\n\004type\030\004 \001(\005\032(\n\004Body\022\021\n\tsessionID\030" +
      "\005 \001(\t\022\r\n\005lists\030\n \003(\tB\n\n\003srcB\003CMCb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bean_CMCRequestParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bean_CMCRequestParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bean_CMCRequestParam_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_com_bean_CMCRequestParam_Header_descriptor =
      internal_static_com_bean_CMCRequestParam_descriptor.getNestedTypes().get(0);
    internal_static_com_bean_CMCRequestParam_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bean_CMCRequestParam_Header_descriptor,
        new java.lang.String[] { "Command", "Sip", "Uuid", "Type", });
    internal_static_com_bean_CMCRequestParam_Body_descriptor =
      internal_static_com_bean_CMCRequestParam_descriptor.getNestedTypes().get(1);
    internal_static_com_bean_CMCRequestParam_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bean_CMCRequestParam_Body_descriptor,
        new java.lang.String[] { "SessionID", "Lists", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
